apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: bankapp
      namespace: bankapp
      jsonPointers:
        - /spec/replicas
  source:
    repoURL: https://github.com/Mujakkir-Pathan/AI-BankApp-DevOps.git
    targetRevision: feat/gitops
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bankapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
